development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redis.142.93.86.230:6379
  #url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  #channel_prefix: homie_production
